version: "2.1"

services:
  ui:
    container_name: ms-ui
    image: ms-ui
    restart: on-failure
    networks:
      - msnetwork
    build:
      context: ./ms-ui
      dockerfile: Dockerfile.ui
    ports:
      - 3000:3000
    depends_on:
      - server
    environment: 
      - NODE_ENV="production"
      - APOLLO_HOST="server"
  server:
    container_name: ms-server
    image: ms-server
    restart: on-failure
    networks:
      - msnetwork
    build:
      context: ./ms-server
      dockerfile: Dockerfile.server
    ports:
      - 4000:4000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment: 
      - NODE_ENV="production"
networks:
  msnetwork:
    driver: bridge
