FROM node:12.17.0-alpine as build
WORKDIR /app
ENV NODE_ENV=production
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN yarn install
RUN yarn build

FROM node:12.17.0-alpine
ENV NODE_ENV=production
ENV space=kk2bw5ojx476
ENV access_token=7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c
ENV api_url=https://cdn.contentful.com/spaces/
WORKDIR /app
COPY package.json ./
RUN yarn install --production
COPY --from=build /app/dist .
EXPOSE 4000
CMD ["node","index.js"]